### PR TITLE
Fix price invalid character issue

### LINKED ISSUE #29: Illigal character in price
the lower i put the profit the faster i get the error. maybe this can help identify the error?

### PR DESCRIPTION
**Pull request by saumitrabhave**
Tries to Fix #29 , #25, #10

### CODE REVIEW

**Comment by Foof811** [comment]
i implemented it into my bot and I'll see what it does

**Comment by Foof811** [comment]
@saumitrabhave

**Comment by Foof811** [comment]
well from the test I did, it didn't give me the illegal character info, but we still need a fix for the insufficient balance error with some method of validating the balance before it attempts to sell so that way it actually goes through and doesn't just kill itself trying to sell nothing.

**Comment by saumitrabhave** [comment]
This issue basically happens because of default system setting which prints the float numbers in scientific exponential format For. eg. '4.08E+10' , this change makes sure that when we call the API the rate is formatted as decimals till satoshis.

The insufficient balance error seems to be because of the flaw in trading algorithm itself, fixing which will deserve a PR of its own, IMHO.

**Pull request merged**
